version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # ローカルの8080ポートをコンテナの8080ポートにマッピング
    volumes:
      - ./app/frontend:/app  # 必要なディレクトリのみマウント
      - /app/node_modules
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORKDIR: app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    entrypoint: ["bash", "-c", "bundle exec rails db:create db:migrate && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"]
    volumes:
      - '.:/app'
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  mysql-data:
    driver: local